[package]
name = "attps_solana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
 
[dependencies]
hex = "0.4.3"
borsh = "1.5.3"
solana-program = "1.18.26"

[dev-dependencies]
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.43.0"

[lints.clippy]
enum_glob_use = "deny"
suspicious = "warn"
unsafe_code = "forbid"