name: ATTPS protocol test

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Solana
      run: sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
      
    - name: Add Solana to PATH
      run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        
    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test -- --nocapture
